name: Update Weather Data
on:
  repository_dispatch:
    types: [trigger_calc]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: pip install requests
      - name: Run calculation
        env:
          OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
          LAT: ${{ github.event.client_payload.lat }}
          LON: ${{ github.event.client_payload.lon }}
          YEARS: ${{ github.event.client_payload.years }}
        run: python calc_weather.py
      - name: Commit and Push
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add data.json
          git commit -m "Update weather data for ${LAT}, ${LON}"
          git push
